version: '3.1'

services:
  mongodb:
    container_name: mongodb
    image: mongo:4
    environment:
        MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_user
        MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
        - db_user
        - db_password
    volumes:
        - mongodb_data_container:/data/db

  sample-data:
    build: .
    command: /app/data
    environment:
        DB_USER_FILE: /run/secrets/db_user
        DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
        - db_user
        - db_password
    depends_on:
      - mongodb

  beer-api:
    container_name: beer-api
    build: .
    command: /app/server
    ports:
      - "8080:8080"
    environment:
        DB_USER_FILE: /run/secrets/db_user
        DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
        - db_user
        - db_password
    depends_on:
      - mongodb
      - sample-data

secrets:
    db_user:
        file: db_user.txt
    db_password:
        file: db_password.txt

volumes:
    mongodb_data_container: