apiVersion: v1
kind: Service
metadata:
  name: beer-review
  labels:
    app: server
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: server