apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mongodb
        image: mongo:4
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/secret/db_user.txt
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/secret/db_password.txt
        ports:
        - containerPort: 27017
          name: database
        volumeMounts:
        - name: data
          mountPath: /data/db
        - name: secret
          mountPath: /etc/secret
          readOnly: true
      volumes:
      - name: secret
        secret:
          secretName: db-user-pass
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

